### ISSUE TITLE
Add support for stormpath.web.social config options

### ISSUE THREAD

**Issue by timothyej** [stormpath/stormpath-node-config#32]
Add support for new [`stormpath.web.social`](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#implementing-page-based-workflows) configuration.

Part of https://github.com/stormpath/express-stormpath/issues/298.

**Comment by robertjd** [comment]
FYI I've opened this, as I think we have more that needs to be addressed: https://github.com/stormpath/stormpath-framework-spec/pull/35

**Comment by robertjd** [comment]
The framework spec was updated, please see here for the new structure:

https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml#L196-L207
