### ISSUE TITLE
postLoginHandler returns old data

### ISSUE THREAD

**Issue by RobAWilkinson** [stormpath/stormpath-node-config#50]
Receiving an error with the email verification strategy, currently, the user account on stormpath is marked as enabled post verification, but the postLoginHandler in my app still has the status as `UNVERIFIED`

**Comment by RobAWilkinson** [comment]
This issue was due to undocumented default caching with the node sdk. Need to document this somehow

**Comment by robertjd** [comment]
Hi @RobAWilkinson , was this the problem that happens when the email verification link is pointing to api.stormpath.com?

**Comment by RobAWilkinson** [comment]
Yes, I didnt change the link at all. Fixed this by changing the cache ttl
and tti to 1 second for now.

**Comment by robertjd** [comment]
Thanks for the update, this is a known issue right now, I hope we didn't waste too much of your time while you looked for the problem :( Are you planning to continue using api.stormpath.com for the links?

**Comment by RobAWilkinson** [comment]
for the time being, yes, I would love to move away from that flow eventually,
