### ISSUE TITLE
cannot read property 'getGroup' of undefined.

### ISSUE THREAD

**Issue by epferrari** [stormpath/stormpath-node-config#65]
When initializing the app with express-stormpath, it immediately fails with this error:

```
.../node_modules/express-stormpath/node_modules/stormpath-config/lib/strategy/EnrichIntegrationFromRemoteConfigStrategy.js:155
          outerScope.client.getGroup(href, function(err, group) {
                           ^

TypeError: Cannot read property 'getGroup' of undefined
```

Upon looking into it, it appears `outerScope.client` is never set in *EnrichIntegrationFromRemoteConfigStrategy.js*. In this context, `outerScope` is an alias for the `Enrich` instance. So by changing line 240 from

```
var client = this.clientFactory(config);
```

to 

```
var client = this.client = this.clientFactory(config);
```

I was able to overcome the error. Is this a reasonable alteration? Or are we expecting that there is a `client` already on the `Enrich...` instance at that point?

**Comment by jibiabraham** [comment]
@epferrari For what it's worth, I found that I could hit this error consistently if I set the default account store of my Stormpath application as any `Group` resource. When I changed this to an `Organization`, I do not get this error

**Comment by robertjd** [comment]
Thanks @epferrari and @jibiabraham for the report!  I can confirm that error when a group is mapped as the default account store, and taht @epferrari 's fix works.  I've issued a PR for this, stay tuned for a new release.

@epferrari are you using this library with express-stormpath?

**Comment by epferrari** [comment]
@robertjd Thanks for fixing. Yes, I'm using with express-stormpath.

**Comment by robertjd** [comment]
Hi @epferrari , thanks for the ping.  This is now released, you may need to upgrade your `stormpath` dependency to `0.19.1`, please let me know if you run into any issues.

**Comment by epferrari** [comment]
Will do, thanks for the update!
